# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vmGm04UrynWzA_VGCMSYCC4U3Omsjb2
"""

#01  try to exteact  data from index 1 to index 300 with ajump 3

s= "this my first python programming  class and i am lerning python string  and  its function"

s[1:300:3]

# 02 try to reverse a string with out using  reversed function

s[::-1]

# 03 try to split a string  after conversion of entire  string in uppercase

s1 =s. upper()
s1.split()

#04 try to convert whoole string  in to lower case

s.lower()

# 05 the try to capetelize whole string

s.capitalize()

# 06 write the difference between isalnum() and isalpha

# isalnum () - this function checks that if all  the charecters in  the string  are alphanumeric   if yes print it oprint true else it
# note - spaces in between alphanumeric  charecters  case  the out put  of the code  to be false.

# isalpha() -   this function cheks  that if all the  cherectors  in the string  alphabets  if yes is print  true else is print
# note -  spaces in between alphabet  charecters causr  the out put of the code  to be false

#07 try to  give example of expand tab

#exampleof expand tab function

s2="Hi i\t t here\ t my \ t name\t is \t ayush,\tnice\tto\tmeet \t you\shubham!!"

s2.expandtabs() #by defalt it is 8 spaces per tab

#08 give and example of strip, lstrip and rstrip.

# 1 - example of strip:

a = "@@@2@heyy!! ayush@2@@@"
a.strip("@2") #  removes all @2 from both the sides

# 09 replace a strinh charecter  by another charecter by taking your own example"your name"

name= "ayush"

name.replace("ayush","shubham")

#10 try to givr defination of string  center function with an example.

#definition

# center ()function is used to align the string in to the center by  adding spacefied cerectors in both the the sides of the string
# then the string will the specified width and if the total width  is greater than the length  of the string  thr extra charectors
#to both sides ( or witdh on extra either  sides if width is an old number or string has old number of chaecters).

#example

b= "ayush"

b.center(130,"*")

b.center(200,"*")

# write the defination of the compailer interoretor in vour own words.

#copiler:=The code which we have written in the program gets converted into binary code(01) by the compiler because the computer knows only binary
           # language. So basicaly compiler converts our code into binary code so that the code gets exicuted by the computer.

#Interpretor - It reads our code line by line and executs it immediately in a sequence manner and interpriting the code at the run time.

# 12 Python is an interpreted of compiled language give clear ans.

#  Python code is executed by an interpreter like CPython which reads and executes the code line by line at runtime. This is why Python
#  is considered an interpreted language.

# 13 Try to write a usecase of python with your understanding.

# There are many usecases of python such as:

# 1. Pyhton is used in Cybersecurity.
# 2. Python is used in Web development.   ( Django, Flask for building websites.)
# 3. Python is used in Data analysis and mashin learning.   (Pandas, TensorFlow for data analysis and AI.)
# 4. Python is used in Artifitial intelligence (Generative AI).
# 5. Python is used in Internet Of Things (IOT).
# 6. Python is used in Cloud computing.   ( Automating cloud services)
# 7. Python is used in Game development.   (Pygame for game prototyping.)
# 8. Python is used in Blockchain development.

